name: 'Chromatic Publish on PR'

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main

jobs:
  chromatic:
    if: contains(github.event.pull_request.labels.*.name, 'components')
    name: 'Chromatic Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: node
    
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          run_install: true

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          # Grab this from the Chromatic manage page
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      - name: Comment on PR
        if: success()
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ## Storybook Preview
            [View Storybook](${{ steps.chromatic.outputs.storybookUrl }})
            [View Chromatic](${{ steps.chromatic.outputs.buildUrl }})